### ISSUE TITLE
Whitespace in filepath

### ISSUE THREAD

**Issue by nicolashohm** [hgraca/sublime-text-2-php-refactor#6]
i'm using win 7 and if i use the refactor function the diff file opens and show me the following:

```
Could not open input file: 'C:\Users\johndoe\AppData\Roaming\Sublime
```

it seems you have to escape the space

**Comment by hgraca** [comment]
Hi,

Are you using the latest version of the plugin? 
Last week I merged a pull request that would fix that...

**Comment by nicolashohm** [comment]
jep version 1.2.1 at 15a84fd85db51dd10e499745f2bcc0cc04349b67

**Comment by hgraca** [comment]
Ok, I'll try to take a look asap, but I dont have much time, and I dont even have a window$ VM , so unfortunatly it might take a while. :(

**Comment by nicolashohm** [comment]
ok i saw the change, but it doesn't help so i'll also take a look maybe i can fix it ;)

**Comment by hgraca** [comment]
cool! :)
