### ISSUE TITLE
Sublime Text 3

### ISSUE THREAD

**Issue by ivank** [hgraca/sublime-text-2-php-refactor#9]
Any idea if this will be converted to ST3 ? It does not work at the moment

**Comment by hgraca** [comment]
Hi, I'm not usinf ST anymore so I'm not gonna touch it ...
You are wellcome to pick up where I left it :-)

Enviado de Samsung Mobile

-------- Mensagem original --------
De : Ivan Kerin notifications@github.com 
Data:26/03/2014  15:38  (GMT+01:00) 
Para: hgraca/sublime-text-2-php-refactor sublime-text-2-php-refactor@noreply.github.com 
Assunto: [sublime-text-2-php-refactor] Sublime Text 3 (#9) 

Any idea if this will be converted to ST3 ? It does not work at the moment

**Comment by ivank** [comment]
Well I might just do it :), Out of curiosity, which editor did you convert to?

**Comment by hgraca** [comment]
I'm using phpStorm and it's the best I ever tried. Its slower than Sublime
when starting up, but after that its as fast and it has all the sublime
functionality. They are even going to add the multi select in version 8.

Herberto Graça

---

http://pt.linkedin.com/pub/herberto-gra%C3%A7a/8/10/b32

2014-04-01 8:59 GMT+02:00 Ivan Kerin notifications@github.com:
